### ISSUE TITLE
Add setting

### ISSUE THREAD

**Issue by videobelu** [mtnbkr88/3M50ThermostatController#1]
Possibility to set the display in degrees Celsius or Fahrenheit

Thanks (very good job)

**Comment by mtnbkr88** [comment]
Thank you for the compliment. There is no API to do this in the thermostat interface and Fahrenheit values are used throughout my code so this would not be a simple change. Unfortunately I currently don't have the time to rewrite the code. Please accept my apologies.

**Comment by videobelu** [comment]
Thanks for the answer ....i suppose the variation is to implement in app
....is your code available ?I am not a programmer but i think to try using
MIT App inventor if you can share your code .
Thanks
Fabrizio

Il sab 20 mag 2023, 02:57 mtnbkr88 ***@***.***> ha scritto:

**Comment by mtnbkr88** [comment]
I just uploaded a new version where one can choose Celsius or Fahrenheit.

**Comment by videobelu** [comment]
Oh thank you very much ....you are my hero !
Fabrizio

Il ven 26 mag 2023, 22:22 mtnbkr88 ***@***.***> ha scritto:
